# -*- coding: utf-8 -*-
"""DataScienceII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/IvanSerem/ds2-proyecto-agricola/blob/main/DataScienceII.ipynb

# 🌾 Proyecto – Data Science II  
## Contextualización Climática del Rendimiento Agrícola en Argentina (2014–2023)

---

## 1️⃣ Antecedentes – Data Science I

En la primera etapa del proyecto (Data Science I) se desarrolló un modelo predictivo agrícola capaz de estimar el rendimiento de distintos cultivos a partir de variables del suelo y condiciones climáticas.

Se trabajó con más de 36.000 registros correspondientes al período 2014–2023, construyendo un pipeline completo de Ciencia de Datos que culminó con un modelo **CatBoost Regressor**, obteniendo las siguientes métricas:

- **R² ≈ 0.9787**
- **MAE ≈ 2.30**
- **RMSE ≈ 3.79**

**Acceso al modelo**:
[Predictor Agrícola Inteligente](https://huggingface.co/spaces/IvanSerem/PREDICTOR-DE-RENDIMIENTO-AGRICOLA)

Estos resultados evidenciaron una alta capacidad predictiva y estabilidad del modelo.

Sin embargo, el dataset original provenía de Kaggle y representaba una base estructurada y preprocesada, lo que limitaba el análisis del contexto climático real argentino.

---

## 2️⃣ Evolución del Proyecto

En Data Science I, la pregunta central fue:

> ¿Es posible determinar, a partir de los valores del suelo y las condiciones climáticas, si una cosecha será fructífera?

En esta segunda etapa, el enfoque evoluciona hacia una contextualización climática real:

> ¿Cómo se caracterizan los patrones climáticos reales ocurridos en Argentina entre 2014 y 2023 y qué implicancias potenciales podrían tener para el rendimiento agrícola a nivel provincial?

El objetivo ya no es únicamente predecir rendimiento, sino comprender el entorno climático estructural donde esos rendimientos ocurren.

---

## 3️⃣ Construcción del Dataset Climático

Para esta etapa se incorporaron datos reales obtenidos mediante la API oficial **NASA POWER**, construyendo un dataset climático consolidado (2014–2023) que incluye:

- Temperatura media diaria (T2M)
- Temperatura máxima y mínima
- Precipitación diaria (PRECTOTCORR)
- Velocidad del viento (WS2M)
- Humedad relativa (RH2M)
- Ubicación geográfica por provincia

### Características del dataset:

- **83.996 registros**
- **23 provincias**
- **10 años completos de datos diarios**

Este dataset permite analizar el comportamiento climático real argentino desde una perspectiva estructural y comparativa.

---

## 4️⃣ Alcance Analítico

El análisis desarrollado en esta etapa incluye:

- Análisis univariado
- Análisis bivariado
- Análisis multivariado
- Estudio de rachas de lluvia
- Análisis estacional
- Evaluación de correlaciones estructurales
- Identificación de agrupamientos climáticos provinciales

Este enfoque permite detectar patrones, variabilidad regional y eventos potencialmente relevantes para la planificación agrícola.

---

## 5️⃣ Justificación del Estudio

El rendimiento agrícola no depende únicamente del suelo, sino también del comportamiento climático acumulado y de la ocurrencia de eventos extremos.

Factores como:

- Rachas prolongadas de lluvia  
- Sequías estacionales  
- Humedad persistente  
- Vientos intensos  
- Variaciones térmicas  

pueden alterar significativamente el resultado productivo, incluso cuando el suelo presenta condiciones óptimas.

Comprender la dinámica climática argentina permite:

- Interpretar mejor los resultados del modelo predictivo desarrollado en Data Science I.
- Detectar provincias con mayor riesgo climático estructural.
- Identificar patrones regionales diferenciados.
- Evaluar tendencias de variabilidad en precipitación y temperatura.
- Contextualizar potenciales riesgos productivos.

---

## 🎯 Objetivo del Proyecto – Data Science II

Analizar y caracterizar los patrones climáticos reales ocurridos en Argentina durante el período 2014–2023, utilizando datos provenientes de APIs oficiales, con el fin de contextualizar el rendimiento agrícola y detectar estructuras climáticas relevantes a nivel provincial.

---

# 🔎 Preguntas de Investigación – Análisis Climático Provincial (2014–2023)

## 🌡️ Temperatura

1. ¿Cuáles son las provincias con mayor temperatura media anual durante el período analizado?
2. ¿Existe una relación entre la temperatura media anual y la precipitación total anual en las distintas provincias de Argentina?

## 🌧️ Precipitación

3. ¿Cuáles son las provincias con mayor precipitación acumulada promedio?
4. ¿Cómo se distribuye la precipitación diaria a lo largo del período estudiado?
5. ¿La precipitación se concentra en pocos eventos intensos o se distribuye de manera uniforme en el tiempo?
6. ¿Qué provincias presentan mayor cantidad de eventos o rachas de lluvia durante el período 2014–2023?
7. ¿Cuál es la frecuencia de días sin precipitaciones?

## 💧 Humedad

8. ¿Cuáles son las provincias con mayor humedad relativa promedio?
9. ¿Existe una relación entre la humedad relativa media y la precipitación anual?

## 💨 Viento

10. ¿Qué provincias presentan el mayor porcentaje de días con viento intenso?

## 📊 Análisis Multivariable

11. ¿Se observan agrupamientos naturales de provincias con características climáticas similares?
12. ¿Qué relaciones estructurales se identifican entre temperatura, precipitación, viento y humedad a nivel provincial?

## 🗺️ Visualización Espacial

13. ¿Cómo se distribuyen espacialmente las principales variables climáticas mediante un mapa interactivo provincial?

14. ¿Es posible identificar perfiles climáticos diferenciados entre las provincias argentinas a partir de sus variables promedio de temperatura, precipitación, viento y humedad durante el período 2014–2023?

## 1.1 Importación de Librerías y Definición de Parámetros

### 🔹 Introducción

En esta sección importamos las librerías necesarias para la manipulación de datos, visualización y consumo de APIs.  
Además, definimos los parámetros temporales que delimitarán nuestro análisis, permitiendo mantener coherencia y control sobre el rango de información a consultar.
"""

# Importamos las librerías esenciales
import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns

# Configuramos un estilo visual para todos nuestros gráficos
sns.set_theme(style="whitegrid")

# Definimos los parámetros de la petición
url_base = "https://power.larc.nasa.gov/api/temporal/daily/point"
años_a_consultar = list(range(2014, 2024))

"""### 🔹 Conclusión

Como se observa, se establece un rango de años entre 2014 y 2023 inclusive, lo que nos permite analizar una década completa de datos climáticos.  

Este recorte temporal asegura consistencia histórica y facilita comparaciones interanuales en etapas posteriores del análisis.

---

## 1.2 Extracción de Datos en Lotes

### 🔹 Introducción

Para facilitar la manipulación y evitar errores en la consulta de datos, realizamos la extracción de información en lotes anuales.  

La solicitud se ejecuta iterando sobre los años definidos previamente y utilizando las coordenadas de latitud y longitud correspondientes a distintas provincias argentinas.  

Este enfoque permite mantener control sobre el volumen de datos descargados y reduce el riesgo de fallos en la conexión o limitaciones de la API.
"""

import pandas as pd
import requests
import time

# =========================
# Configuración base NASA POWER
# =========================
url_base = "https://power.larc.nasa.gov/api/temporal/daily/point"
años_a_consultar = list(range(2014, 2024))

# Provincias argentinas (capital provincial como punto representativo)
provincias = {
    "Buenos Aires": (-34.61, -58.38),
    "Catamarca": (-28.47, -65.78),
    "Chaco": (-27.45, -58.99),
    "Chubut": (-43.30, -65.10),
    "Córdoba": (-31.42, -64.18),
    "Corrientes": (-27.47, -58.83),
    "Entre Ríos": (-31.73, -60.53),
    "Formosa": (-26.18, -58.17),
    "Jujuy": (-24.18, -65.33),
    "La Pampa": (-36.62, -64.29),
    "La Rioja": (-29.41, -66.86),
    "Mendoza": (-32.89, -68.83),
    "Misiones": (-27.37, -55.90),
    "Neuquén": (-38.95, -68.06),
    "Río Negro": (-40.81, -63.00),
    "Salta": (-24.78, -65.41),
    "San Juan": (-31.53, -68.52),
    "San Luis": (-33.30, -66.34),
    "Santa Cruz": (-51.62, -69.22),
    "Santa Fe": (-31.63, -60.70),
    "Santiago del Estero": (-27.78, -64.27),
    "Tierra del Fuego": (-54.80, -68.30),
    "Tucumán": (-26.82, -65.22)
}

# Acá guardamos TODO (todas las provincias, todos los años)
lista_dataframes = []

print("--- Realizando la petición en lotes (por provincia y por año) con NASA POWER ---")

for provincia, (lat, lon) in provincias.items():
    print(f"\n📍 Provincia: {provincia} | lat={lat}, lon={lon}")

    for anio in años_a_consultar:
        print(f"  Obteniendo datos para el año {anio}...")

        params = {
            "latitude": lat,
            "longitude": lon,
            "start": f"{anio}0101",
            "end": f"{anio}1231",
            "parameters": "T2M,T2M_MAX,T2M_MIN,PRECTOTCORR,WS2M,RH2M",
            "community": "AG",
            "format": "JSON"
        }

        try:
            response = requests.get(url_base, params=params, timeout=60)
            response.raise_for_status()

            payload = response.json()

            # NASA POWER no trae "data": trae "properties/parameter"
            data_params = payload["properties"]["parameter"]

            # data_params: {variable: {YYYYMMDD: valor}}
            df_anual = pd.DataFrame(data_params)

            # convertir índice YYYYMMDD a fecha
            df_anual["date"] = pd.to_datetime(df_anual.index, format="%Y%m%d")
            df_anual["anio"] = anio
            df_anual["provincia"] = provincia
            df_anual["lat"] = lat
            df_anual["lon"] = lon

            lista_dataframes.append(df_anual.reset_index(drop=True))
            print(f"    ✅ Datos {provincia} {anio}: {len(df_anual)} registros.")

            time.sleep(0.2)

        except requests.exceptions.RequestException as e:
            print(f"    ❌ Error en {provincia} {anio}: {e}")

"""### 🔹 Conclusión

La extracción segmentada por año y por ubicación geográfica garantiza mayor estabilidad en el proceso de adquisición de datos.  

Además, este método facilita futuras validaciones, reprocesamientos parciales y control de calidad en etapas posteriores del proyecto.API.

---

## 1.3 Inspección de los Resultados del Bucle

### 🔹 Introducción

Antes de consolidar todos los datos en un único DataFrame, es fundamental verificar qué información fue recolectada durante la ejecución del bucle.

La variable `lista_dataframes` debería contener un DataFrame por cada año consultado exitosamente.  
Por ello, realizamos una inspección inicial para validar:

- Cantidad de DataFrames recolectados.
- Estructura del primer DataFrame.
- Forma (filas y columnas).
- Primeras observaciones del conjunto de datos.

Esta etapa nos permite detectar posibles errores antes de avanzar a la concatenación final.
"""

# Verificamos cuántos DataFrames hemos recolectado
# Debería ser uno por cada año que no dio error.
print(f"Se han recolectado {len(lista_dataframes)} DataFrames en total.")

# Inspeccionemos el primer DataFrame de la lista para ver su estructura y contenido
# Este corresponde a los datos del primer año que consultamos (2020)
if lista_dataframes:
    print("\n--- Analizando el PRIMER DataFrame de la lista (datos del año 2020) ---")

    # Seleccionamos el primer elemento de la lista
    primer_df = lista_dataframes[0]

    # Mostramos su forma y sus primeras filas
    print(f"Forma del primer DataFrame: {primer_df.shape}")
    print("Primeras 3 filas:")
    display(primer_df.head(3))

"""### 🔹 Conclusión

Esta verificación preliminar nos permite asegurar que la extracción de datos fue exitosa y que cada año consultado generó un DataFrame con la estructura esperada.

Validar la cantidad de elementos y revisar la forma del primer DataFrame reduce el riesgo de errores posteriores en la etapa de concatenación y análisis exploratorio (EDA).

De esta manera, mantenemos control sobre la calidad y consistencia de los datos desde las primeras fases del proyecto.

---

## 1.4 Consolidación y Verificación

### 🔹 Introducción

Una vez completada la extracción en lotes, procedemos a consolidar todos los DataFrames almacenados en `lista_dataframes` en una única tabla maestra.

Para ello utilizamos `pd.concat()`, lo que nos permite unificar la información de todas las provincias y años en un solo DataFrame estructurado.

Posteriormente realizamos una verificación inicial para validar:

- Dimensión del dataset final
- Tipos de datos
- Cobertura temporal
- Cantidad de provincias incluidas

Este paso es fundamental para confirmar la integridad del conjunto de datos antes de avanzar hacia etapas de limpieza o análisis exploratorio.
"""

# 1.4. Consolidación y Verificación

# Verificamos que la lista no esté vacía antes de continuar
if lista_dataframes:
    # Unimos todos los DataFrames (todas las provincias y años)
    df_clima_crudo = pd.concat(lista_dataframes, ignore_index=True)

    print("\n--- ¡DataFrame Consolidado Creado Exitosamente! ---")
    print(f"Forma del DataFrame final: {df_clima_crudo.shape}")

    # Información general para un primer diagnóstico
    print("\n--- Información General ---")
    df_clima_crudo.info()

    # Verificación rápida de cobertura
    print("\n--- Verificaciones básicas ---")
    print("Provincias incluidas:", df_clima_crudo["provincia"].nunique())
    print("Años incluidos:", df_clima_crudo["anio"].unique())
    print("Rango de fechas:", df_clima_crudo["date"].min(), "→", df_clima_crudo["date"].max())
else:
    print("No se pudieron cargar los datos.")

"""### 🔹 Conclusión

El proceso de consolidación generó un dataset con 83.996 registros y 11 variables, cubriendo 23 provincias argentinas y un período completo entre 2014 y 2023.

La verificación confirma que:

- No existen valores nulos iniciales.
- Las variables climáticas fueron correctamente tipadas como numéricas.
- La variable de fecha fue reconocida como tipo `datetime`.
- La cobertura temporal es consistente y continua.

Con esta estructura consolidada, el dataset se encuentra listo para avanzar hacia la fase de limpieza optimizada (Data Wrangling) y posterior Análisis Exploratorio de Datos (EDA).

---

# Módulo 2: Data Wrangling del Dataset Climático

El dataset climático proveniente de la API NASA POWER presenta una estructura tabular organizada, sin datos anidados ni metadata técnica redundante.

Sin embargo, para su correcta utilización en análisis exploratorio y modelado predictivo, resulta necesario optimizar su estructura, estandarizar su semántica y enriquecer sus variables.

En este módulo se realiza el proceso de Data Wrangling, orientado a transformar el dataset crudo en una base analítica consistente y preparada para la toma de decisiones.

---

## Acciones realizadas

### 🔹 1. Selección de Variables (Feature Selection)

Se conservaron únicamente las variables climáticas relevantes para el análisis agrícola, eliminando columnas que no aportaban valor directo al objetivo del proyecto.

Esta reducción de dimensionalidad mejora la eficiencia computacional y simplifica el análisis posterior.

---

### 🔹 2. Estandarización y Renombrado de Columnas

Las variables originales fueron renombradas bajo una nomenclatura clara y coherente en español, facilitando la interpretación y comunicación del análisis.

Este ajuste semántico mejora la legibilidad del código y reduce la ambigüedad conceptual.

---

### 🔹 3. Transformación de Tipos de Datos

Se verificaron y ajustaron los tipos de datos, especialmente la variable temporal, asegurando su correcta conversión al formato `datetime`.

Una tipificación adecuada permite realizar análisis temporales, agregaciones y segmentaciones con precisión.

---

### 🔹 4. Creación de Nuevas Variables (Feature Engineering)

Se generaron variables derivadas a partir de las originales, incluyendo conversiones de unidades y componentes temporales.

El objetivo fue enriquecer el dataset para capturar patrones climáticos relevantes que puedan influir en el rendimiento agrícola y en futuros modelos predictivos.

## 2.1 Exploración Inicial de Columnas

### 🔹 Introducción

Antes de realizar cualquier proceso de selección o transformación, es importante inspeccionar la estructura del dataset consolidado.

En este caso, listamos todas las columnas presentes en `df_clima_crudo` para:

- Identificar las variables disponibles.
- Verificar consistencia en los nombres.
- Detectar posibles campos innecesarios.
- Preparar la etapa de selección y renombrado.

Esta inspección nos permite entender con precisión la composición del dataset antes de modificarlo.
"""

for columna in df_clima_crudo.columns:
  print(columna)

"""### 🔹 Conclusión

El dataset contiene variables climáticas principales (temperatura, precipitación, viento, humedad), variables temporales y variables geográficas.

Esta estructura confirma que contamos con información suficiente para realizar análisis temporal, espacial y climático, lo que permitirá avanzar hacia una selección de variables estratégicamente orientada al objetivo agrícola del proyecto.

---

## 2.2 Selección y Renombrado de Variables Climáticas

### 🔹 Introducción

Las variables originales del dataset proveniente de NASA POWER se encuentran expresadas en nomenclatura científica y terminología técnica en inglés.

Si bien son correctas desde el punto de vista académico, para facilitar la interpretación, el análisis y la comunicación del proyecto, se procede a:

- Seleccionar únicamente las columnas relevantes.
- Renombrar las variables con una semántica clara en español.
- Mantener coherencia conceptual para etapas posteriores de modelado.

Este proceso mejora la legibilidad del código y fortalece la calidad analítica del dataset.
"""

# ============================================
# MÓDULO 2 – DATA WRANGLING
# Dataset Climático – NASA POWER
# ============================================

import pandas as pd

# ------------------------------------------------
# 1. PARTIMOS DEL DATAFRAME CRUDO
# ------------------------------------------------
# Se asume que df_clima_crudo ya fue creado en el Módulo 1
# (adquisición y consolidación de datos)

print("Forma del DataFrame crudo:")
print(df_clima_crudo.shape)

# ------------------------------------------------
# 2. SELECCIÓN DE COLUMNAS RELEVANTES
# ------------------------------------------------
columnas_relevantes = [
    "T2M",
    "T2M_MAX",
    "T2M_MIN",
    "PRECTOTCORR",
    "WS2M",
    "RH2M",
    "date",
    "anio",
    "provincia",
    "lat",
    "lon"
]

df_clima_limpio = df_clima_crudo[columnas_relevantes].copy()

print("\nColumnas seleccionadas:")
print(df_clima_limpio.columns)

# ------------------------------------------------
# 3. RENOMBRADO DE COLUMNAS (CLARIDAD SEMÁNTICA)
# ------------------------------------------------
df_clima_limpio = df_clima_limpio.rename(columns={
    "T2M": "temp_media",
    "T2M_MAX": "temp_max",
    "T2M_MIN": "temp_min",
    "PRECTOTCORR": "precipitacion",
    "WS2M": "vel_viento",
    "RH2M": "humedad",
    "date": "fecha",
    "anio": "anio",
    "provincia": "provincia",
    "lat": "latitud",
    "lon": "longitud"
})

# ------------------------------------------------
# 4. VERIFICACIÓN GENERAL DEL DATASET
# ------------------------------------------------
print("\n--- Información del DataFrame Limpio ---")
df_clima_limpio.info()

print("\n--- Primeras filas del DataFrame Limpio ---")
df_clima_limpio.head()

"""### 🔹 Conclusión

El dataset fue reducido a las variables climáticas esenciales y renombrado bajo una nomenclatura clara y coherente en español.

Este ajuste:

- Mejora la interpretación de resultados.
- Facilita la comunicación del análisis.
- Reduce fricción cognitiva en etapas de EDA y modelado.
- Prepara el dataset para futuras transformaciones y generación de variables derivadas.

Con esta estructura semántica optimizada, el DataFrame se encuentra listo para continuar con la fase de Feature Engineering y análisis exploratorio.

## 2.3 Conversión de Velocidad del Viento a km/h

### 🔹 Introducción

La variable original `vel_viento` se encuentra expresada en metros por segundo (m/s), unidad estándar utilizada en datos meteorológicos internacionales.

Sin embargo, para facilitar la interpretación práctica y hacer los valores más intuitivos dentro del contexto local, se decide convertir esta métrica a kilómetros por hora (km/h).

La conversión se realiza multiplicando por 3.6, dado que:

1 m/s = 3.6 km/h

Además, se redondea el resultado a un decimal para mejorar la legibilidad sin perder precisión relevante.
"""

df_clima_limpio["vel_viento_kmh"] = (
    df_clima_limpio["vel_viento"] * 3.6
).round(1)

df_clima_limpio.head()

"""La nueva variable `vel_viento_kmh` permite una lectura más clara y alineada con el sistema de medición comúnmente utilizado en Argentina.

Este tipo de transformación mejora la interpretabilidad del dataset sin alterar la información original, y resulta especialmente útil en contextos productivos donde la velocidad del viento impacta directamente en actividades agrícolas.

Con esta variable derivada, el dataset gana claridad operativa y queda mejor preparado para análisis descriptivos y modelos predictivos.

---

## Conclusión del Módulo

Este proceso de Data Wrangling convierte un conjunto de datos crudo en una base estructurada, optimizada y analíticamente robusta.

Más allá de la limpieza técnica, este módulo establece los fundamentos para un análisis exploratorio sólido y para el desarrollo de modelos predictivos confiables.

# 📊 Módulo 3: EDA y Data Storytelling  

Con el dataset ya limpio, estructurado y enriquecido en el módulo anterior, entramos ahora en una etapa clave del proceso de Ciencia de Datos: **el Análisis Exploratorio de Datos (EDA)** y la construcción de una narrativa basada en evidencia.

En este módulo comenzamos a **hacerle preguntas concretas a los datos** y utilizamos visualizaciones para responderlas de forma clara e interpretativa.

El objetivo no es solo observar números, sino:

- 🔎 Detectar patrones climáticos relevantes  
- 🌧️ Identificar comportamientos de lluvia, humedad, viento y temperatura  
- 📈 Analizar relaciones entre variables  
- 🧠 Comprender dinámicas regionales  
- 📖 Transformar los datos en una historia comprensible  

El **EDA** nos permite entender la estructura interna del dataset antes de modelar.  
El **Data Storytelling** nos ayuda a comunicar esos hallazgos con claridad.

En esta etapa analizamos:

- Provincias más cálidas  
- Provincias con mayor precipitación acumulada  
- Distribución de lluvias diarias  
- Relación entre humedad y lluvia  
- Eventos intensos y rachas  
- Riesgo de evaporación  
- Frecuencia de viento fuerte  
- Visualización geográfica interactiva  

Cada gráfico responde una pregunta específica.  
Cada métrica aporta contexto.

## ¿Cuáles son las Provincias con Mayor Temperatura Media?

Como parte del Análisis Exploratorio de Datos (EDA), se analiza la temperatura media anual (`T2M`) por provincia para identificar cuáles presentan los valores promedio más elevados durante el período 2014–2023.

Este análisis permite:

- Detectar patrones climáticos regionales.
- Identificar zonas con mayor acumulación térmica.
- Comprender posibles impactos en la producción agrícola.

Para ello, se calcula la media de temperatura por provincia y se ordenan los resultados de mayor a menor.
"""

# ==============================
# TOP 10 PROVINCIAS MÁS CALUROSAS
# ==============================

# 1️⃣ Calculamos la temperatura promedio por provincia
top_10_calor = (
    df_clima_crudo
    .groupby("provincia")["T2M"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

# 2️⃣ Visualización
plt.figure(figsize=(12, 8))

sns.barplot(
    y=top_10_calor.index,
    x=top_10_calor.values,
    palette="viridis"
)

plt.title("Top 10 Provincias Más Calurosas (Promedio T2M 2014–2023)", fontsize=16)
plt.xlabel("Temperatura Media (°C)", fontsize=12)
plt.ylabel("Provincia", fontsize=12)

plt.show()

# 3️⃣ Mostrar valores numéricos
display(top_10_calor)

"""### 🔹 Conclusión y Observación de los Datos

El análisis revela que las provincias del noreste argentino (Formosa, Chaco, Corrientes y Misiones) lideran el ranking de temperaturas medias más elevadas.

También se destacan provincias del noroeste como Tucumán y Santiago del Estero, lo que confirma la influencia de factores climáticos regionales característicos de zonas subtropicales y semiáridas.

La diferencia térmica entre la primera y la décima provincia no es extremadamente amplia, lo que indica que gran parte del norte argentino mantiene promedios térmicos elevados de manera sostenida.

Desde una perspectiva agrícola, estas condiciones pueden:

- Favorecer cultivos que requieren alta acumulación térmica.
- Incrementar el riesgo de estrés hídrico si no se acompaña con niveles adecuados de precipitación.
- Impactar en la planificación de calendarios productivos.

Este resultado confirma la coherencia climática esperada y valida la consistencia del dataset consolidado.

---

## ¿Cuales son las Provincias con Mayor Precipitación Acumulada?

En esta sección del Análisis Exploratorio de Datos (EDA), se estudia la precipitación total acumulada por provincia durante el período 2014–2023.

El objetivo es identificar cuáles regiones presentan mayor disponibilidad hídrica a lo largo de la década analizada.

A diferencia del análisis anterior de temperatura media, en este caso se realiza una agregación por suma, ya que interesa conocer el volumen total de lluvia acumulado en milímetros.

Este análisis es clave para comprender:

- La distribución regional de recursos hídricos.
- El potencial agrícola por disponibilidad de agua.
- La exposición a eventos de exceso hídrico.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================
# TOP 10 PROVINCIAS MÁS LLUVIOSAS
# (PRECIPITACIÓN TOTAL ACUMULADA)
# ==============================

# 1) Agregación: suma de precipitación por provincia
top_10_lluvia = (
    df_clima_crudo
    .groupby("provincia")["PRECTOTCORR"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

# 2) Plot
plt.figure(figsize=(12, 8))

sns.barplot(
    y=top_10_lluvia.index,
    x=top_10_lluvia.values,
    palette="viridis"
)

plt.title("Top 10 Provincias con Más Precipitación (Acumulado 2014–2023)", fontsize=16)
plt.xlabel("Precipitación Total Acumulada (mm)", fontsize=12)
plt.ylabel("Provincia", fontsize=12)

# 3) Formato de ticks para que se lea mejor
plt.ticklabel_format(style='plain', axis='x')  # evita notación científica
plt.grid(True, axis="x", linestyle="--", alpha=0.3)

plt.show()

# 4) Mostrar valores numéricos
display(top_10_lluvia.to_frame(name="precipitacion_total_mm"))

"""El análisis muestra que la provincia de Misiones lidera ampliamente el ranking de precipitación acumulada, lo cual es consistente con su clima subtropical húmedo.

Las provincias del noreste argentino (NEA) —Misiones, Formosa, Chaco y Corrientes— concentran los mayores volúmenes de lluvia, confirmando una marcada diferencia respecto a regiones más áridas del país.

También se observa la presencia de provincias de la región pampeana como Santa Fe y Buenos Aires, lo que refuerza su relevancia productiva en términos agrícolas.

Desde una perspectiva agroclimática, estas provincias presentan:

- Alta disponibilidad hídrica sostenida.
- Potencial favorable para cultivos extensivos.
- Mayor riesgo de excesos hídricos y eventos extremos en determinados períodos.

El patrón observado resulta coherente con la distribución climática argentina y valida la consistencia del dataset analizado.

---

## ¿Existe una relación entre la temperatura media anual y la precipitación total anual en las distintas provincias de Argentina?


En este bloque de código se realiza un análisis exploratorio para evaluar la relación entre **temperatura media anual** y **precipitación total anual** en distintas provincias de Argentina a lo largo del período estudiado.

Primero, los datos climáticos crudos se agrupan por **provincia y año**, calculando:

- La **temperatura media anual** (promedio de `T2M`).
- La **precipitación total anual acumulada** (suma de `PRECTOTCORR`).

Luego, se construye un **gráfico de dispersión** que permite visualizar cómo se relacionan ambas variables para cada combinación provincia-año.

Este tipo de visualización es útil para detectar patrones generales, posibles correlaciones y comportamientos atípicos que podrían influir en la productividad agrícola.

---
"""

import matplotlib.pyplot as plt

# 1️⃣ Agrupamos por provincia y año
df_simple = (
    df_clima_crudo
    .groupby(["provincia", "anio"], as_index=False)
    .agg(
        temp_media=("T2M", "mean"),
        lluvia_total=("PRECTOTCORR", "sum")
    )
)

# 2️⃣ Creamos gráfico simple
plt.figure(figsize=(8,6))
plt.scatter(df_simple["temp_media"], df_simple["lluvia_total"], alpha=0.6)

plt.title("Temperatura media vs Lluvia total (Provincia-Año)")
plt.xlabel("Temperatura media (°C)")
plt.ylabel("Precipitación total anual (mm)")

plt.show()

"""## Conclusión del Análisis

A partir del gráfico obtenido se observa:

- Una **tendencia general positiva moderada**: provincias con mayores temperaturas medias tienden a presentar mayores niveles de precipitación acumulada.
- Existe una **alta dispersión de los datos**, lo que indica que la relación no es perfectamente lineal.
- Se identifican algunos puntos con **precipitaciones excepcionalmente altas**, que podrían representar regiones con climas más húmedos o eventos extremos.

En términos agrícolas, esto sugiere que ciertas regiones combinan **temperaturas elevadas y buena disponibilidad hídrica**, condiciones que pueden favorecer determinados cultivos. Sin embargo, la variabilidad observada indica que el rendimiento productivo dependerá también de otros factores complementarios como el tipo de suelo, manejo agronómico y especie cultivada.

---

# ¿Cuál es la Evolución de la Precipitación Total en Argentina (2014–2023)?

Hasta ahora vimos comparaciones por provincia, pero ahora hacemos una pregunta más macro:

¿Cómo evolucionó la lluvia total en Argentina a lo largo del tiempo?

Este análisis nos permite:
- Detectar años más húmedos o más secos
- Observar posibles tendencias
- Identificar anomalías climáticas
- Evaluar estabilidad o variabilidad interanual
"""

import matplotlib.pyplot as plt

# 1️⃣ Agrupamos por año
lluvia_anual = (
    df_clima_crudo
    .groupby("anio", as_index=False)
    .agg(lluvia_total=("PRECTOTCORR", "sum"))
)

# 2️⃣ Creamos gráfico de línea
plt.figure(figsize=(10,6))
plt.plot(lluvia_anual["anio"], lluvia_anual["lluvia_total"], marker="o")

plt.title("Evolución de la Precipitación Total en Argentina (2014–2023)")
plt.xlabel("Año")
plt.ylabel("Precipitación total acumulada (mm)")
plt.xticks(lluvia_anual["anio"])

plt.show()

# Mostrar valores numéricos
display(lluvia_anual)

"""## Observaciones de los datos

- Se observa una **alta variabilidad interanual**.
- Los años **2014 y 2016** presentan valores elevados de precipitación.
- A partir de **2018** se aprecia una caída significativa.
- **2020 y especialmente 2022** muestran valores considerablemente más bajos.
- **2023** evidencia una leve recuperación.

Esto indica que el régimen de lluvias **no es estable** y presenta ciclos o fluctuaciones importantes.

## ¿Qué significa esto para un productor agrícola?

- Hay años con mayor disponibilidad hídrica.
- Hay años con posible **estrés hídrico**.
- No se puede asumir un comportamiento lineal del clima.
- La variabilidad climática debe considerarse en la planificación productiva.
- La gestión del riesgo (riego, reservas de agua, cultivos adaptados) se vuelve clave.

---

## ¿Hay una Relación entre Humedad Relativa y Precipitación Anual?

En esta sección se analiza la relación entre la humedad relativa media anual y la precipitación total acumulada por provincia y año.

El objetivo es evaluar si existe una asociación estadística entre:

- La humedad promedio del ambiente.
- El volumen total de lluvia acumulada en el año.

Para ello:

1. Se agrupan los datos por provincia y año.
2. Se calcula la humedad media anual.
3. Se calcula la precipitación total anual.
4. Se visualiza la relación mediante un gráfico de dispersión.
5. Se calcula la correlación utilizando los métodos de Pearson y Spearman.

Este análisis permite detectar patrones climáticos estructurales y validar coherencia interna del dataset.
"""

import matplotlib.pyplot as plt

# 1️⃣ Agrupamos por provincia y año
df_humedad = (
    df_clima_crudo
    .groupby(["provincia", "anio"], as_index=False)
    .agg(
        humedad_media=("RH2M", "mean"),
        lluvia_total=("PRECTOTCORR", "sum"),
        lluvia_media=("PRECTOTCORR", "mean")
    )
)

# 2️⃣ Scatter simple
plt.figure(figsize=(8,6))
plt.scatter(df_humedad["humedad_media"], df_humedad["lluvia_total"], alpha=0.6)

plt.title("Humedad media vs Lluvia total (Provincia-Año)")
plt.xlabel("Humedad relativa media (%)")
plt.ylabel("Precipitación total anual (mm)")

plt.show()

# 3️⃣ Correlación
corr_pearson = df_humedad["humedad_media"].corr(df_humedad["lluvia_total"])
corr_spearman = df_humedad["humedad_media"].corr(df_humedad["lluvia_total"], method="spearman")

print(f"Correlación Pearson: {corr_pearson:.3f}")
print(f"Correlación Spearman: {corr_spearman:.3f}")

"""El gráfico de dispersión muestra una tendencia positiva clara: a medida que aumenta la humedad relativa media anual, también tiende a incrementarse la precipitación total acumulada.

Los coeficientes obtenidos:

- **Correlación de Pearson ≈ 0.64**
- **Correlación de Spearman ≈ 0.63**

Indican una correlación positiva moderada-alta entre ambas variables.

Esto sugiere que:

- Provincias más húmedas suelen registrar mayores volúmenes de lluvia.
- Existe coherencia física en los datos (consistencia climatológica).
- La humedad puede funcionar como variable explicativa relevante en futuros modelos predictivos.

Desde una perspectiva agroclimática, esta relación es esperable: regiones con mayor disponibilidad hídrica suelen presentar mayores niveles de humedad ambiental sostenida.

---

## ¿Como es la Distribución de la Precipitación Diaria?

En esta sección se analiza la distribución de la precipitación diaria durante el período 2014–2023.

A diferencia de los análisis anteriores, que se centraron en valores agregados (medias o acumulados), aquí se estudia la frecuencia con la que ocurren distintos niveles de lluvia diaria.

El objetivo es comprender:

- Cómo se distribuyen los eventos de lluvia.
- Si predominan días secos o lluvias intensas.
- La presencia de valores extremos.

Para ello, se construye un histograma utilizando la variable `PRECTOTCORR`.
"""

import matplotlib.pyplot as plt
import numpy as np

# ==========================================
# HISTOGRAMA DE PRECIPITACIÓN DIARIA
# ==========================================

plt.figure(figsize=(10,6))

plt.hist(df_clima_crudo["PRECTOTCORR"], bins=50)

plt.title("Distribución de la Precipitación Diaria (2014–2023)")
plt.xlabel("Precipitación diaria (mm)")
plt.ylabel("Frecuencia")

plt.show()

"""## ¿Cuál es la frecuencia de dias sin precipitacion?

En esta sección se analiza la proporción de días sin lluvia dentro del período total estudiado.

El objetivo es cuantificar qué tan frecuente es la ausencia de precipitaciones, lo cual permite comprender mejor la distribución real del régimen hídrico anual.

Más allá del volumen total de lluvia acumulada, resulta clave responder:

**¿Con qué frecuencia ocurren días sin precipitaciones dentro del período analizado?**

Este indicador es relevante para el sector agrícola, ya que no solo importa cuánto llueve en total, sino cómo se distribuyen esos eventos a lo largo del tiempo. Una alta proporción de días secos podría implicar mayor necesidad de riego, estrés hídrico en cultivos o mayor variabilidad productiva.

"""

dias_totales = len(df_clima_crudo)
dias_sin_lluvia = (df_clima_crudo["PRECTOTCORR"] == 0).sum()

print("Días totales:", dias_totales)
print("Días sin lluvia:", dias_sin_lluvia)
print("Porcentaje de días sin lluvia:",
      round(dias_sin_lluvia / dias_totales * 100, 2), "%")

lluvia_total = df_clima_crudo["PRECTOTCORR"].sum()

dias_intensos = df_clima_crudo[df_clima_crudo["PRECTOTCORR"] > 20]

lluvia_intensa_total = dias_intensos["PRECTOTCORR"].sum()

print("Lluvia total acumulada:", round(lluvia_total, 2), "mm")
print("Lluvia en días intensos (>20mm):", round(lluvia_intensa_total, 2), "mm")
print("Porcentaje del agua que cayó en días intensos:",
      round(lluvia_intensa_total / lluvia_total * 100, 2), "%")

"""### 🔹 Resultados Obtenidos

- **Días totales analizados:** 83.996  
- **Días sin lluvia:** 42.585  
- **Porcentaje de días sin lluvia:** 50,7 %

- **Lluvia total acumulada:** 189.388 mm  
- **Lluvia en días intensos (>20 mm):** 95.260 mm  
- **Porcentaje del agua concentrada en días intensos:** 50,3 %


### 🔹 Conclusión y Observación de los Datos

Los resultados muestran un patrón climático altamente concentrado:

- Más del 50 % de los días no registran lluvia.  
- Sin embargo, aproximadamente el 50 % del volumen total de agua cae en días con precipitaciones intensas (>20 mm).

Esto indica que el régimen hídrico no es uniforme, sino que se caracteriza por:

- Alta frecuencia de días secos.  
- Eventos de lluvia concentrados y de alta intensidad.

Desde una perspectiva agroclimática, este patrón puede implicar:

- Mayor riesgo de estrés hídrico entre eventos.  
- Dependencia de lluvias intensas para completar el acumulado anual.  
- Posible aumento del riesgo de erosión o anegamiento en determinados períodos.

---

## ¿Cuáles son las Provincias con Mayor Humedad Relativa Promedio?

En esta sección se analiza la humedad relativa media anual por provincia durante el período 2014–2023.

La humedad relativa es una variable clave en climatología, ya que influye en:

- La sensación térmica.
- La evaporación del agua.
- El desarrollo de cultivos.
- La proliferación de enfermedades fúngicas.

A diferencia de la precipitación, la humedad relativa no mide directamente la cantidad de lluvia, sino la proporción de vapor de agua presente en el aire en relación con su capacidad máxima.

El objetivo es identificar qué provincias presentan los niveles promedio más elevados de humedad ambiental.
"""

# =========================================
# TOP 10 PROVINCIAS CON MAYOR HUMEDAD
# =========================================

import matplotlib.pyplot as plt
import seaborn as sns

# 1️⃣ Promedio de humedad por provincia
humedad_por_provincia = (
    df_clima_crudo
    .groupby("provincia")["RH2M"]
    .mean()
    .sort_values(ascending=False)
)

# 2️⃣ Top 10
top_10_humedad = humedad_por_provincia.head(10)

print("Top 10 Provincias con Mayor Humedad Promedio (2014-2023):")
display(top_10_humedad)

# 3️⃣ Gráfico
plt.figure(figsize=(10, 6))
sns.barplot(
    x=top_10_humedad.values,
    y=top_10_humedad.index,
    palette="coolwarm"
)

plt.title("Top 10 Provincias con Mayor Humedad Promedio (2014–2023)", fontsize=14)
plt.xlabel("Humedad Relativa Promedio (%)")
plt.ylabel("Provincia")
plt.show()

"""### 🔹 Conclusión y Observación de los Datos

El análisis muestra que **Tierra del Fuego** lidera el ranking de humedad relativa promedio, seguida por **Misiones** y provincias patagónicas como **Santa Cruz** y **Chubut**.

Se observan dos patrones interesantes:

- Provincias del noreste argentino (NEA), como **Misiones**, **Chaco** y **Corrientes**, presentan alta humedad asociada a climas subtropicales.
- Provincias del sur del país, como **Tierra del Fuego** y **Santa Cruz**, muestran alta humedad relativa aunque no necesariamente registren los mayores niveles de precipitación.

Esto confirma que la humedad relativa no depende únicamente de la cantidad de lluvia, sino también de factores como:

- Temperatura
- Latitud
- Cercanía al mar

Desde una perspectiva agroclimática, altos niveles de humedad pueden:

- Favorecer determinados cultivos.
- Aumentar el riesgo de enfermedades fúngicas.
- Influir en la planificación de calendarios productivos.

---

## ¿Qué provincias tienen más eventos (rachas) de lluvia a lo largo del período 2014–2023?

El análisis de rachas permite comprender no solo cuánto llueve, sino cómo se distribuye la lluvia en el tiempo.

En el caso de Chubut, se registraron 687 rachas de lluvia durante el período 2014–2023. Esto equivale aproximadamente a 69 rachas por año, es decir, en promedio, el inicio de una secuencia de lluvia cada 5 a 6 días.

Sin embargo, es importante aclarar que una racha no representa un único día de lluvia, sino el comienzo de una secuencia consecutiva de días con precipitación.

Desde una perspectiva productiva, este dato sugiere que:

- La lluvia puede ser relativamente frecuente.
- Los eventos podrían estar fragmentados en secuencias cortas.
- La disponibilidad hídrica dependerá no solo de la frecuencia, sino también de la duración e intensidad de cada racha.

En términos agrícolas, comprender la estructura temporal de la lluvia es más relevante que observar únicamente el acumulado anual, ya que impacta directamente en la infiltración del suelo, la retención de humedad y la planificación del riego.

---
"""

import pandas as pd
import plotly.express as px

# ============================================================
# 0) Asegurar columna de fecha (ajustá si tu columna se llama distinto)
# ============================================================
df = df_clima_crudo.copy()

# Intento de detección automática de columna de fecha
possible_date_cols = ["fecha", "date", "datetime", "time", "timestamp"]
date_col = next((c for c in possible_date_cols if c in df.columns), None)

if date_col is None:
    raise ValueError(
        "No encontré una columna de fecha. "
        "Creá una columna 'fecha' o decime cómo se llama tu columna de fecha."
    )

df[date_col] = pd.to_datetime(df[date_col])

# ============================================================
# 1) Definir días con lluvia y ordenar
# ============================================================
# Umbral: si querés evitar “lloviznas” o ruido, podés usar 0.1 en vez de 0
RAIN_EPS = 0.0
df["llovio"] = df["PRECTOTCORR"] > RAIN_EPS

df = df.sort_values(["provincia", date_col])

# ============================================================
# 2) Detectar INICIO de racha
#    inicio_racha = llovio HOY y NO llovio AYER (dentro de la misma provincia)
# ============================================================
df["llovio_ayer"] = df.groupby("provincia")["llovio"].shift(1, fill_value=False)
df["inicio_racha"] = df["llovio"] & (~df["llovio_ayer"])

# ============================================================
# 3) Contar rachas por provincia
# ============================================================
rachas_prov = (
    df.groupby("provincia", as_index=False)["inicio_racha"]
    .sum()
    .rename(columns={"inicio_racha": "rachas_lluvia"})
    .sort_values("rachas_lluvia", ascending=False)
)

display(rachas_prov.head(10))

# ============================================================
# 4) Gráfico principal: rachas por provincia
# ============================================================
fig = px.bar(
    rachas_prov,
    x="provincia",
    y="rachas_lluvia",
    title="Cantidad de Rachas de Lluvia por Provincia (2014–2023)",
    labels={"provincia": "Provincia", "rachas_lluvia": "Rachas de lluvia (inicio de secuencias)"},
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

# ============================================================
# 5) (Opcional) Resaltar una provincia específica (ej: Chubut)
# ============================================================
prov_obj = "Chubut"
if prov_obj in set(rachas_prov["provincia"]):
    valor = int(rachas_prov.loc[rachas_prov["provincia"] == prov_obj, "rachas_lluvia"].iloc[0])
    print(f"📌 {prov_obj}: {valor} rachas en 2014–2023 (≈ {valor/10:.1f} rachas/año)")
else:
    print(f"⚠️ No encontré '{prov_obj}' en la columna provincia. Revisa el nombre exacto.")

"""Se observa una marcada heterogeneidad en la cantidad de rachas de lluvia entre provincias durante el período analizado.

- **Chubut y Río Negro** presentan los valores más altos (cerca de 700 rachas en el período).
- En el extremo opuesto, **Tierra del Fuego** muestra una cantidad considerablemente menor.
- El grupo central de provincias (Buenos Aires, Misiones, Santa Fe, Entre Ríos, La Pampa, Chaco, Corrientes, entre otras) se mantiene en un rango relativamente estable entre 450 y 500 rachas aproximadamente.


## Interpretación Productiva

Estos resultados sugieren que:

- En provincias como **Chubut**, la lluvia tiende a fragmentarse en múltiples eventos pequeños o secuencias cortas.
- Esto no implica necesariamente mayor volumen total de lluvia, sino mayor **frecuencia de eventos**.
- En provincias con menor cantidad de rachas, la lluvia podría estar más concentrada en eventos más prolongados o menos frecuentes.

## Enfoque Agrícola

Desde una perspectiva productiva:

- Una mayor cantidad de rachas implica mayor frecuencia de inicio de eventos lluviosos.
- Esto impacta en la planificación de siembra, cosecha y manejo de maquinaria.
- También influye en la infiltración del suelo y la retención de humedad.

En términos agrícolas, no solo importa cuánto llueve, sino **cómo se distribuye temporalmente la lluvia**, ya que esa estructura condiciona el rendimiento potencial del cultivo.

---

## Índice de Riesgo de Evaporación: Interpretación Agroclimática

Luego de analizar la precipitación, la humedad y la temperatura por separado, se construye un índice simple de riesgo evaporativo para evaluar la posible pérdida de agua desde el suelo hacia la atmósfera.

El índice se define como:

Índice de evaporación = (Temperatura media × Velocidad del viento) / Humedad relativa

Este indicador no mide evaporación real, sino un potencial relativo de pérdida hídrica, basado en tres factores clave:

- Mayor temperatura → más energía disponible para evaporar.
- Mayor viento → mayor transporte del vapor de agua.
- Menor humedad relativa → mayor capacidad del aire para absorber agua.

El objetivo es comparar provincias en términos de presión climática sobre la humedad del suelo.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1️⃣ Creamos el índice simple de evaporación
df_clima_crudo["indice_evaporacion"] = (
    df_clima_crudo["T2M"] * df_clima_crudo["WS2M"] / df_clima_crudo["RH2M"]
)

# 2️⃣ Promedio por provincia
evap_prov = (
    df_clima_crudo
    .groupby("provincia")["indice_evaporacion"]
    .mean()
    .sort_values(ascending=False)
)

# 3️⃣ Top 10 provincias con mayor riesgo evaporativo
top_10_evap = evap_prov.head(10)

# 4️⃣ Gráfico
plt.figure(figsize=(10,6))
sns.barplot(x=top_10_evap.values, y=top_10_evap.index)

plt.title("Top 10 Provincias con Mayor Índice de Riesgo de Evaporación (2014–2023)")
plt.xlabel("Índice Evaporación (relativo)")
plt.ylabel("Provincia")

plt.show()

# 5️⃣ Mostrar valores
display(top_10_evap)

"""El ranking muestra que provincias como **San Juan, Neuquén y Mendoza** presentan los valores más elevados del índice evaporativo relativo.

Esto es coherente con sus características climáticas:

- Temperaturas elevadas.
- Baja humedad relativa.
- Mayor exposición a viento.
- Climas áridos o semiáridos.

Desde una perspectiva agrícola, un mayor índice de evaporación implica:

- Mayor pérdida potencial de agua del suelo.
- Mayor demanda de riego.
- Menor permanencia de humedad disponible para cultivos.

Este análisis complementa los estudios previos de precipitación y humedad, permitiendo comprender no solo cuánto agua ingresa al sistema, sino también qué tan rápido puede perderse.

---

## ¿Cuáles son las provincias que presentan mayor porcentaje de días con viento intenso?

Además de la lluvia y la evaporación, el viento es un factor clave en el comportamiento climático y productivo.

En este análisis se define **viento fuerte** como aquellos días donde la velocidad supera los **6 m/s** (aproximadamente 21,6 km/h).  

El objetivo es identificar qué provincias presentan mayor porcentaje de días con viento intenso, ya que esto puede influir en:

- Mayor evaporación del suelo.
- Estrés en cultivos.
- Mayor pérdida de humedad superficial.
- Impacto en infraestructura rural.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1️⃣ Definir umbral de viento fuerte
umbral_viento = 6  # m/s

# 2️⃣ Crear columna booleana
df_clima_crudo["viento_fuerte"] = df_clima_crudo["WS2M"] > umbral_viento

# 3️⃣ Calcular porcentaje de días con viento fuerte por provincia
viento_fuerte_por_prov = (
    df_clima_crudo
    .groupby("provincia")["viento_fuerte"]
    .mean() * 100
).sort_values(ascending=False)

# 4️⃣ Mostrar Top 10
top_10_viento = viento_fuerte_por_prov.head(10)

# 5️⃣ Gráfico tipo dot plot (más profesional que barras)
plt.figure(figsize=(10,6))
plt.scatter(top_10_viento.values, top_10_viento.index)

plt.title("Top 10 Provincias con Mayor % de Días con Viento Fuerte (>6 m/s)")
plt.xlabel("Porcentaje de días (%)")
plt.ylabel("Provincia")

plt.show()

# 6️⃣ Mostrar valores numéricos
display(top_10_viento.round(2))

"""### 🔹 Conclusión

Los resultados muestran que **Tierra del Fuego, Chubut y Santa Cruz** lideran el ranking de días con viento fuerte, con valores superiores al 25%.

Esto indica que en estas provincias:

- Más de 1 de cada 4 días presenta viento intenso.
- El ambiente favorece mayor pérdida de humedad.
- El manejo agrícola debe considerar protección contra viento y planificación de riego.

En contraste, provincias del norte presentan porcentajes significativamente menores.

Este análisis complementa los estudios de lluvia y evaporación, mostrando que no solo importa cuánto llueve, sino también qué condiciones ambientales pueden acelerar la pérdida de agua.

---

## Visualización Dinámica: Mapa Interactivo de Variables Climáticas por Provincia

Hasta este punto, los análisis se basaron en gráficos estáticos (barras, dispersión e histogramas) que permiten comparar provincias de forma puntual.  
Para esta ocasión, incorporamos una visualización **más dinámica e interactiva** mediante un **mapa de Argentina con capas**, lo que facilita explorar el comportamiento climático por región y comparar variables directamente sobre el territorio.

El mapa resume promedios provinciales del período 2014–2023 e integra cuatro variables clave:

- **Lluvia promedio** (mm/día)  
- **Temperatura media** (°C)  
- **Viento medio** (km/h)  
- **Humedad promedio** (%)  

El usuario puede activar/desactivar capas para analizar patrones espaciales y, al hacer clic en cada provincia, visualizar un resumen multivariable en un popup.
"""

import folium
print ("Instalado ")

# ============================================================
# MAPA ARGENTINA — Promedios por Provincia
# Variables: Lluvia (mm/día) + Temp (°C) + Viento (km/h) + Humedad (%)
# Requiere: df_clima_crudo con columnas:
#   provincia, PRECTOTCORR, T2M, WS2M, RH2M
# ============================================================

import folium

# -----------------------------
# 1) Agregación por provincia
# -----------------------------
df_prov = (
    df_clima_crudo
    .groupby("provincia", as_index=False)
    .agg(
        lluvia_media=("PRECTOTCORR", "mean"),
        temp_media=("T2M", "mean"),
        viento_ms=("WS2M", "mean"),
        humedad_media=("RH2M", "mean")
    )
)

# Convertir viento de m/s a km/h (como venías trabajando)
df_prov["viento_kmh"] = df_prov["viento_ms"] * 3.6

# -----------------------------
# 2) Coordenadas (centros aproximados por provincia)
# -----------------------------
coordenadas = {
    "Buenos Aires": (-34.61, -58.38),
    "Córdoba": (-31.42, -64.18),
    "Santa Fe": (-31.63, -60.70),
    "Mendoza": (-32.89, -68.84),
    "Tucumán": (-26.83, -65.22),
    "Salta": (-24.78, -65.41),
    "Misiones": (-27.37, -55.90),
    "Chaco": (-27.45, -58.98),
    "Corrientes": (-27.47, -58.83),
    "Formosa": (-26.18, -58.17),
    "Entre Ríos": (-31.73, -60.53),
    "San Juan": (-31.53, -68.52),
    "San Luis": (-33.30, -66.33),
    "La Pampa": (-36.62, -64.29),
    "Río Negro": (-40.81, -63.00),
    "Neuquén": (-38.95, -68.06),
    "Chubut": (-43.30, -65.10),
    "Santa Cruz": (-51.62, -69.22),
    "Tierra del Fuego": (-54.80, -68.30),
    "La Rioja": (-29.41, -66.86),
    "Catamarca": (-28.47, -65.78),
    "Santiago del Estero": (-27.80, -64.26),
    "Jujuy": (-24.19, -65.30),
}

df_prov["lat"] = df_prov["provincia"].map(lambda x: coordenadas.get(x, (None, None))[0])
df_prov["lon"] = df_prov["provincia"].map(lambda x: coordenadas.get(x, (None, None))[1])

faltantes = df_prov[df_prov[["lat", "lon"]].isna().any(axis=1)]["provincia"].unique()
if len(faltantes) > 0:
    print("⚠️ Provincias sin coordenadas (revisar nombres):", list(faltantes))

df_prov = df_prov.dropna(subset=["lat", "lon"]).copy()

# -----------------------------
# 3) Mapa base + capas (FeatureGroup)
# -----------------------------
m = folium.Map(location=[-38.41, -63.61], zoom_start=4, tiles="cartodbpositron")

capa_lluvia = folium.FeatureGroup(name="🌧️ Lluvia promedio (mm/día)", show=True)
capa_temp   = folium.FeatureGroup(name="🌡️ Temperatura media (°C)", show=False)
capa_viento = folium.FeatureGroup(name="💨 Viento medio (km/h)", show=False)
capa_hum    = folium.FeatureGroup(name="💧 Humedad promedio (%)", show=False)

# Normalización simple para tamaños (radio) sin librerías extra
def scale_radius(series, rmin=6, rmax=18):
    smin, smax = float(series.min()), float(series.max())
    if smax == smin:
        return [ (rmin + rmax) / 2 ] * len(series)
    return list(rmin + (series - smin) * (rmax - rmin) / (smax - smin))

df_prov["r_lluvia"] = scale_radius(df_prov["lluvia_media"])
df_prov["r_temp"]   = scale_radius(df_prov["temp_media"])
df_prov["r_viento"] = scale_radius(df_prov["viento_kmh"])
df_prov["r_hum"]    = scale_radius(df_prov["humedad_media"])

# -----------------------------
# 4) Marcadores por capa + popup multivariable
# -----------------------------
for _, row in df_prov.iterrows():
    popup_html = f"""
    <b>{row['provincia']}</b><br>
    🌧️ Lluvia: {row['lluvia_media']:.2f} mm/día<br>
    🌡️ Temp: {row['temp_media']:.2f} °C<br>
    💨 Viento: {row['viento_kmh']:.2f} km/h<br>
    💧 Humedad: {row['humedad_media']:.2f} %
    """

    # Lluvia
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=row["r_lluvia"],
        color="blue",
        fill=True,
        fill_opacity=0.55,
        popup=folium.Popup(popup_html, max_width=260),
        tooltip=f"{row['provincia']} — {row['lluvia_media']:.2f} mm/día"
    ).add_to(capa_lluvia)

    # Temperatura
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=row["r_temp"],
        color="red",
        fill=True,
        fill_opacity=0.55,
        popup=folium.Popup(popup_html, max_width=260),
        tooltip=f"{row['provincia']} — {row['temp_media']:.2f} °C"
    ).add_to(capa_temp)

    # Viento
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=row["r_viento"],
        color="purple",
        fill=True,
        fill_opacity=0.55,
        popup=folium.Popup(popup_html, max_width=260),
        tooltip=f"{row['provincia']} — {row['viento_kmh']:.2f} km/h"
    ).add_to(capa_viento)

    # Humedad
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=row["r_hum"],
        color="green",
        fill=True,
        fill_opacity=0.55,
        popup=folium.Popup(popup_html, max_width=260),
        tooltip=f"{row['provincia']} — {row['humedad_media']:.2f} %"
    ).add_to(capa_hum)

# Agregar capas y control
capa_lluvia.add_to(m)
capa_temp.add_to(m)
capa_viento.add_to(m)
capa_hum.add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

# Mostrar mapa
m

"""El mapa interactivo permite observar con mayor claridad la distribución espacial de las variables climáticas, facilitando comparaciones directas entre regiones.

Se destacan patrones regionales consistentes con los análisis previos:

- El **NEA** tiende a concentrar mayores valores de **lluvia y humedad**, lo que sugiere alta disponibilidad hídrica.
- Regiones **áridas/semiáridas** del oeste y centro muestran condiciones más propensas a pérdida de agua por combinación de **temperatura y viento**.
- Las provincias del sur presentan con frecuencia **vientos más intensos**, lo que puede aumentar el riesgo evaporativo incluso con temperaturas bajas.

Este tipo de visualización complementa los gráficos tradicionales al incorporar el componente geográfico, ofreciendo una herramienta más intuitiva para análisis climático y toma de decisiones en contextos agrícolas.

---
"""

import plotly.express as px

# ============================================================
# 🌦️ CLUSTERS CLIMÁTICOS CON INTERPRETACIÓN HUMANA
# ============================================================

import numpy as np
import pandas as pd
import plotly.express as px

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1️⃣ Resumen por provincia
df_clima_prov = (
    df_clima_crudo
    .groupby("provincia", as_index=False)
    .agg(
        temp_media=("T2M", "mean"),
        lluvia_media=("PRECTOTCORR", "mean"),
        viento_medio=("WS2M", "mean"),
        humedad_media=("RH2M", "mean"),
    )
)

# 2️⃣ Escalado + clustering
features = ["temp_media", "lluvia_media", "viento_medio", "humedad_media"]
X = df_clima_prov[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clima_prov["cluster"] = kmeans.fit_predict(X_scaled)

# ------------------------------------------------------------
# 3️⃣ Interpretación manual basada en promedios
# ------------------------------------------------------------

cluster_labels = {
    0: "Frío y Húmedo",
    1: "Cálido y Seco",
    2: "Templado Intermedio"
}

df_clima_prov["perfil_climatico"] = df_clima_prov["cluster"].map(cluster_labels)

# ------------------------------------------------------------
# 4️⃣ Visualización 2D con nombres reales
# ------------------------------------------------------------

fig2d = px.scatter(
    df_clima_prov,
    x="temp_media",
    y="lluvia_media",
    color="perfil_climatico",
    hover_name="provincia",
    title="Perfiles Climáticos Provinciales (2014–2023)",
    labels={
        "temp_media": "Temperatura media (°C)",
        "lluvia_media": "Precipitación media (mm/día)",
        "perfil_climatico": "Perfil Climático"
    }
)

fig2d.update_traces(marker=dict(size=12, opacity=0.9, line=dict(width=1, color="black")))
fig2d.show()

"""El análisis permite identificar tres perfiles climáticos diferenciados entre las provincias argentinas:

• **Templado Intermedio**: Provincias con temperaturas medias moderadas y niveles de precipitación relativamente elevados. Representan regiones con condiciones climáticas más equilibradas.

• **Cálido y Seco**: Provincias con temperaturas medias más altas pero con menor nivel de precipitación promedio, lo que sugiere mayor exposición a condiciones de estrés hídrico.

• **Frío y Húmedo**: Provincias con temperaturas medias más bajas y niveles variables de precipitación, asociadas principalmente a regiones del sur del país.

En términos generales, se observa una tendencia positiva moderada entre temperatura media y precipitación promedio en ciertos grupos, aunque no de manera uniforme en todo el territorio.

Este agrupamiento confirma la existencia de patrones climáticos estructurales diferenciados a nivel provincial durante el período 2014–2023.

---

## Análisis de Correlación — Promedios Climáticos por Provincia (2014–2023)

Para comprender cómo se relacionan entre sí las variables climáticas principales, calculamos una **matriz de correlación de Pearson** utilizando los promedios por provincia:

- Temperatura media  
- Lluvia media  
- Viento medio  
- Humedad media
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Resumen por provincia
df_prov = (
    df_clima_crudo.groupby("provincia", as_index=False)
    .agg(
        temp_media=("T2M", "mean"),
        lluvia_media=("PRECTOTCORR", "mean"),
        viento_media=("WS2M", "mean"),
        humedad_media=("RH2M", "mean")
    )
)

df_corr_prov = df_prov[["temp_media", "lluvia_media", "viento_media", "humedad_media"]]

corr_prov = df_corr_prov.corr(method="pearson")

print("=== Matriz de correlación (promedios por provincia) ===")
display(corr_prov)

plt.figure(figsize=(7,5))
sns.heatmap(corr_prov, annot=True, cmap="coolwarm", fmt=".2f", vmin=-1, vmax=1)
plt.title("Matriz de correlación (promedios por provincia) — Clima Argentina 2014–2023")
plt.show()

"""🔹 **Temperatura vs Lluvia (0.53)**  
Existe una correlación positiva moderada. En promedio provincial, las zonas más cálidas tienden a presentar mayor lluvia.

🔹 **Lluvia vs Humedad (0.63)**  
Es la relación más fuerte observada. A mayor precipitación, mayor humedad relativa. Esto es coherente desde el punto de vista físico.

🔹 **Temperatura vs Viento (-0.53)**  
Relación negativa moderada. Las provincias más ventosas tienden a ser menos cálidas (principalmente regiones patagónicas).

🔹 **Temperatura vs Humedad (-0.11)**  
Relación débil. La temperatura promedio no explica directamente la humedad promedio a nivel provincial.

🔹 **Viento vs Lluvia (-0.39)**  
Relación negativa moderada. En promedio, provincias más ventosas tienden a tener menor lluvia media.

## ¿Qué nos dice esto para el análisis climático?

- La **humedad está fuertemente asociada a la lluvia**, lo cual valida la consistencia del dataset.
- El **viento aparece como un factor diferenciador regional**.
- La temperatura influye, pero no es la única variable determinante del régimen hídrico.
- No hay multicolinealidad extrema (no hay valores cercanos a ±1), lo cual es positivo si luego usamos estas variables en un modelo de ML.

# Conclusión General – Análisis Climático Provincial (2014–2023)

A lo largo de este proyecto se trabajó con datos climáticos reales obtenidos mediante la API oficial de NASA POWER, con el objetivo de comprender cómo se comporta el clima argentino a nivel provincial y qué implicancias puede tener este comportamiento para el contexto agrícola.

El análisis permitió ir más allá de simples promedios anuales. No solo se observó cuánto llueve o qué temperatura media presenta cada provincia, sino también cómo se distribuyen esos eventos en el tiempo, cómo se relacionan entre sí las distintas variables climáticas y qué patrones estructurales emergen cuando se analizan en conjunto.

Se identificaron diferencias claras entre provincias, tanto en frecuencia de rachas de lluvia como en niveles de humedad, temperatura y viento. El análisis de clustering permitió detectar perfiles climáticos diferenciados, evidenciando que el territorio argentino no presenta un comportamiento homogéneo, sino que se organiza en tipologías ambientales con características propias.

Desde una perspectiva productiva, esto es relevante porque el rendimiento agrícola no depende únicamente del suelo o del volumen total de precipitaciones, sino también de la dinámica temporal del clima. La frecuencia de días secos, la concentración de eventos intensos, la persistencia de humedad o las variaciones térmicas pueden modificar significativamente las condiciones de producción.

En definitiva, este trabajo permitió contextualizar el entorno climático real en el que se desarrollan los cultivos en Argentina. Más que ofrecer una predicción puntual, el análisis aporta comprensión estructural: entender el clima como sistema, reconocer sus patrones y visualizar cómo se distribuyen sus características en el territorio.

Este enfoque complementa el modelo predictivo desarrollado previamente y sienta una base sólida para futuras integraciones entre datos climáticos reales y modelos de rendimiento agrícola.

---
"""